# Generated by Django 3.0.4 on 2020-03-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadesPrincipais',
            fields=[
                ('atp_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('atp_nome', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'atividades_principais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cli_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('neg_codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('cli_nomefantasia_nomecomercial', models.CharField(blank=True, max_length=100, null=True)),
                ('cli_razaosocial_nomecompleto', models.CharField(blank=True, max_length=60, null=True)),
                ('cli_tipopessoa', models.CharField(blank=True, max_length=1, null=True)),
                ('cli_cpf_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('cli_rg_ie', models.CharField(blank=True, max_length=20, null=True)),
                ('cli_tel_ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('cli_tel_ramal', models.CharField(blank=True, max_length=10, null=True)),
                ('cli_tel', models.CharField(blank=True, max_length=10, null=True)),
                ('cli_fax_ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('cli_fax_ramal', models.CharField(blank=True, max_length=10, null=True)),
                ('cli_fax', models.CharField(blank=True, max_length=10, null=True)),
                ('cli_valorminimo', models.CharField(blank=True, max_length=20, null=True)),
                ('cli_site', models.CharField(blank=True, max_length=60, null=True)),
                ('cli_preferencial', models.CharField(blank=True, max_length=1, null=True)),
                ('cli_atividade', models.CharField(blank=True, max_length=45, null=True)),
                ('cli_ativo', models.CharField(blank=True, max_length=1, null=True)),
                ('cli_coef_prova', models.CharField(blank=True, max_length=20, null=True)),
                ('cli_coef_fotolito', models.CharField(blank=True, max_length=20, null=True)),
                ('cli_pendenciafinan', models.CharField(blank=True, max_length=45, null=True)),
                ('cli_chapa', models.CharField(blank=True, max_length=45, null=True)),
                ('cli_os_correcao', models.CharField(blank=True, max_length=1, null=True)),
                ('cli_descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesContatos',
            fields=[
                ('cnt_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cli_codigo', models.PositiveIntegerField()),
                ('cnt_nome', models.CharField(blank=True, max_length=60, null=True)),
                ('cnt_tel_ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('cnt_telefone', models.CharField(blank=True, max_length=10, null=True)),
                ('cnt_tel_ramal', models.CharField(blank=True, max_length=10, null=True)),
                ('cnt_cel_ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('cnt_celular', models.CharField(blank=True, max_length=10, null=True)),
                ('cnt_email', models.CharField(blank=True, max_length=60, null=True)),
                ('cnt_setor', models.CharField(blank=True, max_length=100, null=True)),
                ('cnt_responsavel', models.CharField(blank=True, max_length=1, null=True)),
                ('cnt_idnextel', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'clientes_contatos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesFormatosChapa',
            fields=[
                ('cli_codigo', models.PositiveIntegerField()),
                ('fcp_codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cfc_utiliza', models.CharField(blank=True, max_length=1, null=True)),
                ('cfc_pinca', models.CharField(blank=True, max_length=20, null=True)),
                ('cfc_coef', models.CharField(blank=True, max_length=20, null=True)),
                ('cfc_expessura', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes_formatos_chapa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesFormatosProva',
            fields=[
                ('cli_codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fpr_codigo', models.PositiveIntegerField()),
                ('cfp_valor', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'clientes_formatos_prova',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesServicosUtilizados',
            fields=[
                ('cli_codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('srv_codigo', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'clientes_servicos_utilizados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cores',
            fields=[
                ('cor_valor', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('end_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cli_codigo', models.PositiveIntegerField()),
                ('end_descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('end_tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('end_logradouro', models.CharField(blank=True, max_length=60, null=True)),
                ('end_numero', models.CharField(blank=True, max_length=10, null=True)),
                ('end_complemento', models.CharField(blank=True, max_length=40, null=True)),
                ('end_bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('end_zona', models.CharField(blank=True, max_length=45, null=True)),
                ('end_cep', models.CharField(blank=True, max_length=9, null=True)),
                ('end_cidade', models.CharField(blank=True, max_length=45, null=True)),
                ('end_estado', models.CharField(blank=True, max_length=40, null=True)),
                ('end_referencia', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'enderecos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormatosChapa',
            fields=[
                ('fcp_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fcp_formato', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'formatos_chapa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormatosProva',
            fields=[
                ('fpr_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fpr_papel', models.CharField(blank=True, max_length=20, null=True)),
                ('fpr_valor', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'formatos_prova',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorariosEntrega',
            fields=[
                ('hor_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('hor_horario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'horarios_entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineatura',
            fields=[
                ('lin_valor', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lineatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('msg_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('msg_texto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mensagens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MensagensOpcoes',
            fields=[
                ('mop_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('mop_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('msg_codigo', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mensagens_opcoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Negociacao',
            fields=[
                ('neg_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('neg_nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'negociacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('os_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cli_codigo', models.PositiveIntegerField()),
                ('os_dataabertura', models.DateField()),
                ('os_dataprometida', models.DateField()),
                ('os_hora', models.TimeField()),
                ('up_codigo2', models.CharField(blank=True, max_length=15, null=True)),
                ('usu_login', models.CharField(blank=True, max_length=100, null=True)),
                ('hor_codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('neg_codigo', models.CharField(blank=True, max_length=60, null=True)),
                ('os_status', models.CharField(blank=True, max_length=1, null=True)),
                ('os_correcao', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsArquivos',
            fields=[
                ('arq_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('arq_nome', models.CharField(max_length=60)),
                ('arq_envio', models.CharField(blank=True, max_length=20, null=True)),
                ('arq_tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('arq_programa', models.CharField(blank=True, max_length=50, null=True)),
                ('arq_plataforma', models.CharField(blank=True, max_length=40, null=True)),
                ('arq_print', models.CharField(blank=True, max_length=35, null=True)),
                ('os_codigo', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'os_arquivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsConfirmacao',
            fields=[
                ('com_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cli_codigo', models.PositiveIntegerField()),
                ('os_codigo', models.PositiveIntegerField()),
                ('msg_codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('com_observacaoaprovacao', models.TextField(blank=True, null=True)),
                ('com_endereco', models.TextField(blank=True, null=True)),
                ('com_retirarestudio_entregar', models.CharField(blank=True, max_length=1, null=True)),
                ('com_entregaurgente', models.CharField(blank=True, max_length=1, null=True)),
                ('com_data', models.DateField(blank=True, null=True)),
                ('hor_codigo', models.IntegerField(blank=True, null=True)),
                ('com_observacaoentrega', models.TextField(blank=True, null=True)),
                ('up_codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('com_negociacao', models.CharField(blank=True, max_length=60, null=True)),
                ('com_fotolito', models.FloatField(blank=True, null=True)),
                ('com_provas', models.FloatField(blank=True, null=True)),
                ('com_ctp', models.FloatField(blank=True, null=True)),
                ('com_plusservice', models.FloatField(blank=True, null=True)),
                ('com_total', models.FloatField(blank=True, null=True)),
                ('com_retirarestudio', models.CharField(blank=True, max_length=1, null=True)),
                ('end_codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('mop_codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('com_contato', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'os_confirmacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsCorrecao',
            fields=[
                ('osc_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('os_codigo', models.IntegerField()),
                ('cli_codigo', models.PositiveIntegerField()),
                ('osc_tec_platesetter', models.CharField(blank=True, max_length=1, null=True)),
                ('osc_tec_apogeex', models.CharField(blank=True, max_length=1, null=True)),
                ('osc_tec_aplicacao', models.CharField(blank=True, max_length=1, null=True)),
                ('osc_tec_outro', models.CharField(blank=True, max_length=1, null=True)),
                ('osc_tec_processadora', models.CharField(blank=True, max_length=1, null=True)),
                ('osc_pro_fechamento', models.CharField(blank=True, max_length=1, null=True)),
                ('osc_pro_tracado', models.CharField(blank=True, max_length=1, null=True)),
                ('osc_pro_imagem', models.CharField(blank=True, max_length=1, null=True)),
                ('osc_pro_fonte', models.CharField(blank=True, max_length=1, null=True)),
                ('osc_pro_outro', models.CharField(blank=True, max_length=100, null=True)),
                ('osc_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('osc_ocorrencia', models.TextField(blank=True, null=True)),
                ('osc_natureza', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'os_correcao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsCtp',
            fields=[
                ('ctp_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('imp_codigo', models.PositiveIntegerField()),
                ('ctp_quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('ctp_formatoschapa', models.PositiveIntegerField(blank=True, null=True)),
                ('ctp_pinca', models.FloatField(blank=True, null=True)),
                ('ctp_valor', models.FloatField(blank=True, null=True)),
                ('ctp_forneada', models.CharField(blank=True, max_length=15, null=True)),
                ('ctp_lineatura', models.IntegerField(blank=True, null=True)),
                ('ctp_reticula', models.CharField(blank=True, max_length=45, null=True)),
                ('os_codigo', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'os_ctp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsFotolito',
            fields=[
                ('fot_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('imp_codigo', models.PositiveIntegerField()),
                ('fot_quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('fot_cor', models.CharField(blank=True, max_length=3, null=True)),
                ('fot_largura', models.CharField(blank=True, max_length=15, null=True)),
                ('fot_altura', models.FloatField(blank=True, null=True)),
                ('fot_valor', models.FloatField(blank=True, null=True)),
                ('os_codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('fot_objetivo', models.CharField(blank=True, max_length=50, null=True)),
                ('fot_lineatura', models.IntegerField(blank=True, null=True)),
                ('fot_filme', models.CharField(blank=True, max_length=50, null=True)),
                ('fot_impressao', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'os_fotolito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsImpressos',
            fields=[
                ('imp_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('os_codigo', models.PositiveIntegerField()),
                ('cli_codigo', models.PositiveIntegerField()),
                ('arq_codigo', models.PositiveIntegerField()),
                ('imp_titulo', models.CharField(blank=True, max_length=60, null=True)),
                ('imp_tipomontagem', models.CharField(blank=True, max_length=1, null=True)),
                ('imp_tipo_promo', models.CharField(blank=True, max_length=1, null=True)),
                ('imp_paginas_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_formato_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_cores_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_acabamento_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_montagemtipo_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_figurarfolha_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_posicaofolha_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_corte_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_aberturavertical_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_aberturahorizontal_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_observacao_promo', models.CharField(blank=True, max_length=150, null=True)),
                ('imp_tipo_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_montagem_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_paginas_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_formato_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_cores_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_orientacaopagina', models.CharField(blank=True, max_length=20, null=True)),
                ('imp_infomontagem', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_figurasfolha_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_numeropaginas_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_posicaofolha_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_corte_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_aberturavertical_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_aberturahorizontal_edit', models.CharField(blank=True, max_length=50, null=True)),
                ('imp_observacao_edit', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'os_impressos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsLog',
            fields=[
                ('log_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('os_codigo', models.PositiveIntegerField()),
                ('sts_status', models.CharField(blank=True, max_length=1, null=True)),
                ('log_datahora', models.DateTimeField(blank=True, null=True)),
                ('usu_login', models.CharField(blank=True, max_length=60, null=True)),
                ('log_observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'os_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsPlusService',
            fields=[
                ('plus_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cli_codigo', models.PositiveIntegerField()),
                ('os_codigo', models.PositiveIntegerField()),
                ('plus_diagramacao', models.CharField(blank=True, max_length=1, null=True)),
                ('plus_fechamento', models.CharField(blank=True, max_length=1, null=True)),
                ('plus_scanner', models.CharField(blank=True, max_length=1, null=True)),
                ('plus_perfil', models.CharField(blank=True, max_length=1, null=True)),
                ('plus_calibracao', models.CharField(blank=True, max_length=1, null=True)),
                ('plus_outro', models.CharField(blank=True, max_length=100, null=True)),
                ('plus_valor', models.FloatField(blank=True, null=True)),
                ('plus_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('plus_observacao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'os_plus_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsProvasOutro',
            fields=[
                ('fpo_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('imp_codigo', models.PositiveIntegerField()),
                ('os_codigo', models.PositiveIntegerField(blank=True, null=True)),
                ('fpo_quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('fpo_altura', models.FloatField(blank=True, null=True)),
                ('fpo_largura', models.FloatField(blank=True, null=True)),
                ('fpo_valor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'os_provas_outro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsProvasPadrao',
            fields=[
                ('fpp_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('imp_codigo', models.PositiveIntegerField()),
                ('fpp_quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('fpp_formato', models.PositiveIntegerField(blank=True, null=True)),
                ('fpp_valor', models.FloatField(blank=True, null=True)),
                ('os_codigo', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'os_provas_padrao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsStatus',
            fields=[
                ('sts_status', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('sts_nome', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'os_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicosUtilizados',
            fields=[
                ('srv_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('srv_nome', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'servicos_utilizados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Up',
            fields=[
                ('up_codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('up_nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'up',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usu_login', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('usu_nome', models.CharField(blank=True, max_length=60, null=True)),
                ('usu_senha', models.CharField(max_length=32)),
                ('usu_status', models.CharField(blank=True, max_length=1, null=True)),
                ('usu_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('usu_lastlogin', models.DateTimeField(blank=True, null=True)),
                ('up_codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('usu_excluido', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosPermissoes',
            fields=[
                ('usu_login', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('per_cad_usuario', models.CharField(blank=True, max_length=1, null=True)),
                ('per_con_usuario', models.CharField(blank=True, max_length=1, null=True)),
                ('per_cad_cliente', models.CharField(blank=True, max_length=1, null=True)),
                ('per_con_cliente', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'usuarios_permissoes',
                'managed': False,
            },
        ),
    ]
